### ISSUE TITLE
Convert object tracker to use observations code

### ISSUE THREAD

**Issue by BrettRD** [jtanx/picopterx#106]
Still more to do:
- [x] Implement global coordinates at all (critical, see camera and lidar observation generators)
- [x] Decide on how to handle GPS uncertainty
- [x] Unit tests
- [ ] At least consider rotational uncertainties
- [x] Object/observation distinguishing routine (a bit basic at the moment)
- [x] Re-jig basic trajectory algorithm
- [x] Mathematics for velocity interpolation

**Comment by BrettRD** [comment]
Ignore GPS uncertainty and use the object's velocity uncertainty to allow the objects to drift.

**Comment by BrettRD** [comment]
Tracker now has a decent matching algorithm, and a couple of braindead ones.
Rotational uncertainties are now firmly on the after-2015 list along with optical flow and hyperbolic distributions.
